### ISSUE TITLE
Rawhide please :P.

### ISSUE THREAD

**Issue by LyesSaadi** [TomaszGasior/mushrooms-rpms#15]
Hi !

Is it possible to provide a repository for rawhide users :P ?

**Comment by TomaszGasior** [comment]
I will try today. Thanks for info.

**Comment by TomaszGasior** [comment]
I enabled rawhide and started builds. I don't know whether it will be successful. For now I'm closing. Please write pkg name you are interested in if build will fail for them.

**Comment by LyesSaadi** [comment]
Thank you ! Everything was successful apparently ;) (except jpeg-archive)
