### ISSUE TITLE
[firefox-developer-edition-bin]

### ISSUE THREAD

**Issue by TomaszGasior** [TomaszGasior/mushrooms-rpms#7]
Is it allowed to use precompiled binary from Mozilla website?
Maybe just package shell script for ~/.local/opt installer?

---

Decision: write bash script which downloads binaries from mozilla.org and provide icon+symbolic icon for it.

**Comment by LyesSaadi** [comment]
It is allowed, not a great idea though.

There's this [copr](https://copr.fedorainfracloud.org/coprs/wanzenbug/firefox-nightly/) and its associated [GitHub](https://github.com/WanzenBug/firefox-nightly-copr) if you want to use their spec file.

(Which is itself derived from this [copr](https://copr.fedorainfracloud.org/coprs/sramanujam/firefox-nightly/))

**Comment by TomaszGasior** [comment]
Thanks for info. I have an idea to package ONLY script which wraps fx command and downloads binary fro mozilla's server. This way we can get updates directly from vendor. It's especially important for Fx Dev because it gets updates more often than standard release.
