### ISSUE TITLE
nautilus-admin don't work on Fedora 38

### ISSUE THREAD

**Issue by Tuxman2** [TomaszGasior/mushrooms-rpms#70]
Hello,

could you add support for nautilus-admin on Fedora 38 ?

Thanks.

**Comment by TomaszGasior** [comment]
The fact that nautilus-admin does not work in Fedora 38 is expected: https://github.com/TomaszGasior/mushrooms-rpms/commit/c4e91e0b7da1b96ef6aa786542ae5f89603c4611

Fedora 38 uses GTK4-based Nautilus but the nautilus-admin extension is designed for GTK3 Nautilus.

However, there is some active fork of that plugin which brigs GTK4 compatibility: https://github.com/MacTavishAO/nautilus-admin-gtk4
This may be doable to change upstream in my RPM package.

**Comment by Tuxman2** [comment]
Hello,

ok. Could you do the change in your RPM package soon ?

Thanks.

**Comment by TomaszGasior** [comment]
It's done. nautilus-admin is available for Fedora 38.
